version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker/sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost/d:rw
      - ./certs:/etc/nginx/vhost.d:rw
      - ./html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: '1'

networks:
  web:
    external:
      name: web
